version: "2"
services: 
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-lets
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

  nginx-proxy:
    container_name: lemp-proxy
    image:  jwilder/nginx-proxy:alpine
    restart: always
    volumes: 
      # - ./proxy-config:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

    ports: 
      # - host:container
      - "80:80"
      - "443:443"

volumes:
  certs:
  vhost:
  html:

networks:
  default:
    external:
      name: microservice_network
