version: "2"

services: 
  email_rpc:
    container_name: email_rpc
    build: python/
    restart: always

    networks:
    - microservice
    - default

  smtp:
    container_name: email_smtp
    image: bytemark/smtp
    restart: always
    environment: 
      RELAY_HOST: smtp-relay.gmail.com
      RELAY_PORT: 587
      RELAY_USERNAME: ${EMAIL}
      RELAY_PASSWORD: ${PASSWORD}

networks: 
  defalut:
    external: 
      name: email_network
  microservice:
    external: 
      name: microservice_network