version: "2"

services: 
  regiser:
    container_name: register_gateway
    build: python/
    restart: always
    ports:
      - "7001:80" 
networks:
  default:
    external:
      name: microservice_network